// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Model.Models
{
    public partial class ecommerceDBContext : DbContext
    {
        public ecommerceDBContext()
        {
        }

        public ecommerceDBContext(DbContextOptions<ecommerceDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Shipping> Shipping { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Variant> Variant { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Products>(entity =>
            {
                entity.HasKey(e => e.IdProduct)
                    .HasName("PK__Products__BA39E84FD6D31CD7");

                entity.Property(e => e.IdProduct)
                    .ValueGeneratedNever()
                    .HasColumnName("id_product");

                entity.Property(e => e.Descriptions)
                    .HasMaxLength(255)
                    .HasColumnName("descriptions");

                entity.Property(e => e.Price)
                    .HasColumnType("decimal(10, 2)")
                    .HasColumnName("price");

                entity.Property(e => e.Product)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("product");
            });

            modelBuilder.Entity<Rol>(entity =>
            {
                entity.HasKey(e => e.IdRol)
                    .HasName("PK__Rol__6ABCB5E037F87EA1");

                entity.Property(e => e.IdRol)
                    .ValueGeneratedNever()
                    .HasColumnName("id_rol");

                entity.Property(e => e.UserType)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<Sales>(entity =>
            {
                entity.HasKey(e => e.IdSales)
                    .HasName("PK__Sales__CB70593B788010E7");

                entity.Property(e => e.IdSales)
                    .ValueGeneratedNever()
                    .HasColumnName("id_Sales");

                entity.Property(e => e.DateSale)
                    .HasColumnType("date")
                    .HasColumnName("date_sale");

                entity.Property(e => e.IdUser).HasColumnName("id_user");

                entity.HasOne(d => d.IdUserNavigation)
                    .WithMany(p => p.Sales)
                    .HasForeignKey(d => d.IdUser)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Sales__id_user__534D60F1");
            });

            modelBuilder.Entity<Shipping>(entity =>
            {
                entity.HasKey(e => e.IdShipping)
                    .HasName("PK__Shipping__46726EE9204AEB5F");

                entity.Property(e => e.IdShipping)
                    .ValueGeneratedNever()
                    .HasColumnName("id_shipping");

                entity.Property(e => e.Destination)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("destination");

                entity.Property(e => e.IdProduct).HasColumnName("id_product");

                entity.Property(e => e.IdSales).HasColumnName("id_Sales");

                entity.Property(e => e.StateEnvio)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("state_envio");

                entity.HasOne(d => d.IdProductNavigation)
                    .WithMany(p => p.Shipping)
                    .HasForeignKey(d => d.IdProduct)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Shipping__id_pro__5629CD9C");

                entity.HasOne(d => d.IdSalesNavigation)
                    .WithMany(p => p.Shipping)
                    .HasForeignKey(d => d.IdSales)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Shipping__id_Sal__571DF1D5");
            });

            modelBuilder.Entity<Users>(entity =>
            {
                entity.HasKey(e => e.IdUser)
                    .HasName("PK__Users__D2D14637471A1A69");

                entity.HasIndex(e => e.Mail, "UQ__Users__7A212904CC211AE2")
                    .IsUnique();

                entity.Property(e => e.IdUser).HasColumnName("id_user");

                entity.Property(e => e.IdRol).HasColumnName("id_rol");

                entity.Property(e => e.Lastname)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("lastname");

                entity.Property(e => e.Mail)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("mail");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("name");

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnName("password");

                entity.HasOne(d => d.IdRolNavigation)
                    .WithMany(p => p.Users)
                    .HasForeignKey(d => d.IdRol)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Users__id_rol__5070F446");
            });

            modelBuilder.Entity<Variant>(entity =>
            {
                entity.HasKey(e => e.IdVariant)
                    .HasName("PK__variant__0B24D7A75A89BA03");

                entity.ToTable("variant");

                entity.Property(e => e.IdVariant)
                    .ValueGeneratedNever()
                    .HasColumnName("id_variant");

                entity.Property(e => e.Color)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("color");

                entity.Property(e => e.Descriptions)
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnName("descriptions");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}