// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Products
    {
        public Products()
        {
            ShippingProducts = new HashSet<ShippingProducts>();
        }

        public int IdProduct { get; set; }
        public string Product { get; set; }
        public string Descriptions { get; set; }
        public decimal Price { get; set; }

        public virtual ICollection<ShippingProducts> ShippingProducts { get; set; }
    }
}