// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Sales
    {
        public Sales()
        {
            Shipping = new HashSet<Shipping>();
        }

        public int IdSales { get; set; }
        public DateTime DateSale { get; set; }
        public int IdUser { get; set; }

        public virtual Users IdUserNavigation { get; set; }
        public virtual ICollection<Shipping> Shipping { get; set; }
    }
}