// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Sales
    {
        public int IdSales { get; set; }
        public DateTime DateSale { get; set; }
        public int IdUser { get; set; }
        public int IdShipping { get; set; }

        public virtual Shipping IdShippingNavigation { get; set; }
        public virtual Users IdUserNavigation { get; set; }
    }
}