// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Shipping
    {
        public Shipping()
        {
            Sales = new HashSet<Sales>();
            ShippingProducts = new HashSet<ShippingProducts>();
        }

        public int IdShipping { get; set; }
        public string Destination { get; set; }
        public string StateEnvio { get; set; }

        public virtual ICollection<Sales> Sales { get; set; }
        public virtual ICollection<ShippingProducts> ShippingProducts { get; set; }
    }
}