// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Shipping
    {
        public int IdShipping { get; set; }
        public string Destination { get; set; }
        public string StateEnvio { get; set; }
        public int IdProduct { get; set; }
        public int IdSales { get; set; }

        public virtual Products IdProductNavigation { get; set; }
        public virtual Sales IdSalesNavigation { get; set; }
    }
}