// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Variant
    {
        public int IdVariant { get; set; }
        public string Color { get; set; }
        public string Descriptions { get; set; }
    }
}